version: "3.2"

services:
  backend:
    container_name: backend
    hostname: backend
    image: node:13-alpine
    working_dir: /app/src
    volumes:
      - ../../backend:/app
    command: sh -c "npm i && npm start"
    environment:
      HOST: "${HOST_BACKEND}"
      PORT: "${PORT_BACKEND}"
    ports:
      - "80:3005"