version: "3"

services:

  fabricbeat:
    image: balazsprehoda/fabricbeat:v4-alpha
    # To make resolution of peer container addresses simple (demo purposes!)
    # In production, you probably want to deploy fabricbeat to the same network
    # as the Hyperledger Fabric containers.
    network_mode: host
    environment:
      - ORG_NUMBER=1
      - PEER_NUMBER=0
      - NETWORK=basic
    volumes:
      # Fabricbeat configuration file
      - ./fabricbeat/fabricbeat.yml:/go/src/github.com/blockchain-analyzer/agent/fabricbeat/fabricbeat.yml
      # Connection profile ("connectionProfile" in configuration file)
      - ./connection-profile-1.yaml:/go/src/github.com/blockchain-analyzer/network/basic/connection-profile-1.yaml
      # Crypto-config
      - ../hfb/crypto-config:/go/src/github.com/blockchain-analyzer/network/basic/crypto-config
      # Kibana dashboard directory ("dashboardDirectory" in configuration file)
      - ../dashboards/7/dashboard:/go/src/github.com/blockchain-analyzer/dashboards/7/dashboard
      # Kibana template directory ("templateDirectory" in configuration file)
      - ./kibana_templates:/go/src/github.com/blockchain-analyzer/agent/kibana_templates
      # Note that if you change "dashboardDirectory", you have to change setup.dashboards.directory accordingly!

