version: "3.2"

networks:
  el-network:

volumes:
  prometheus_data: {}
  grafana_storage: {}

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ../../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    networks:
      - el-network

  pushGateway:
    image: prom/pushgateway
    container_name: pushGateway
    ports:
      - "9091:9091"
    networks:
      - el-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3003:3000
    volumes:
      - grafana_storage:/var/lib/grafana
      - ../../monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ../../monitoring/grafana/config.monitoring
    restart: always
    networks:
      - el-network

  cadvisor:
    image: google/cadvisor:v0.27.4
    privileged: true
    container_name: cadvisor
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      # - /cgroup:/cgroup:ro
    ports:
      - 8080:8080
    restart: always
    networks:
      - el-network